# -*- mode: python -*-

block_cipher = None


a = Analysis(['HospitalGenerator\\run.py'],
             pathex=['C:\\Users\\Jenne\\Documents\\GitHub\\HospitalGenerator',
             'C:\\CocosEnv\\Python27\\Lib\\site-packages\\scrapy\\extensions',
             'C:\\CocosEnv\\Python27\\Lib\\site-packages\\scrapy',
             'C:\CocosEnv\Python27\Lib',
             'C:\\CocosEnv\\Python27\\Lib\\site-packages\\scrapy\\downloadermiddlewares',
             'C:\\Users\\Jenne\\Documents\\GitHub\\HospitalGenerator\\HospitalGenerator'
             ],
             binaries=[],
             datas=[('C:\\CocosEnv\\Python27\\Lib\\site-packages\\scrapy\\mime.types','mime.types')],
             hiddenimports=['scrapy.spiderloader', 'scrapy.statscollectors',
             'scrapy.logformatter', 'scrapy.extensions.closespider',
             'scrapy.pipelines',
             'scrapy.pipelines.ItemPipelineManager',
             'HospitalGenerator.pipelines',
             'scrapy.extensions.feedexport',
             'scrapy.extensions.memdebug',
             'scrapy.extensions.memusage',
             'scrapy.extensions.logstats',
             'scrapy.extensions.telnet',
             'scrapy.extensions.corestats',
             'scrapy.extensions.spiderstate',
             'scrapy.extensions.throttle',
             'scrapy.core.scheduler',
             'scrapy.core.downloader',
             'scrapy.downloadermiddlewares.robotstxt',
             'scrapy.downloadermiddlewares.httpauth',
             'scrapy.downloadermiddlewares.downloadtimeout',
             'scrapy.downloadermiddlewares.defaultheaders',
             'scrapy.downloadermiddlewares.useragent',
             'scrapy.downloadermiddlewares.retry',
             'scrapy.downloadermiddlewares.ajaxcrawl',
             'scrapy.downloadermiddlewares.redirect',
             'scrapy.downloadermiddlewares.chunked',
             'scrapy.downloadermiddlewares.cookies',
             'scrapy.downloadermiddlewares.decompression',
             'scrapy.downloadermiddlewares.httpcache',
             'scrapy.downloadermiddlewares.httpcompression',
             'scrapy.downloadermiddlewares.httpproxy',
             'scrapy.downloadermiddlewares.stats',
             'scrapy.downloadermiddlewares.useragent',
             'scrapy.spidermiddlewares.depth',
             'scrapy.spidermiddlewares.httperror',
             'scrapy.spidermiddlewares.offsite',
             'scrapy.spidermiddlewares.referer',
             'scrapy.spidermiddlewares.urllength',
             'scrapy.dupefilters',
             'queuelib',
             'scrapy.squeues',
             'scrapy.core.downloader.handlers.http',
             'scrapy.core.downloader.contextfactory',
             'htmlentitydefs',
             'robotparser'
             ],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='run',
          debug=False,
          strip=False,
          upx=True,
          console=True )
